# Generated by Django 3.0.8 on 2022-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Done', 'Done')], max_length=200),
        ),
    ]
