# Generated by Django 3.0.8 on 2022-12-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0002_auto_20221207_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Accept', 'Accept'), ('Done', 'Done')], max_length=200),
        ),
    ]
