# Generated by Django 4.1.4 on 2022-12-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0005_alter_consult_id_alter_consultroomreservation_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consult',
            new_name='ConsultReservation',
        ),
        migrations.DeleteModel(
            name='ConsultRoomReservation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
