# Generated by Django 4.1.4 on 2022-12-16 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0005_alter_consult_id_alter_consultroomreservation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=200)),
                ('consult_lab_date', models.DateTimeField(blank=True, null=True)),
                ('form_update_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('intro', models.CharField(max_length=400)),
                ('materials', models.CharField(max_length=400)),
                ('procedure', models.CharField(max_length=400)),
                ('results', models.CharField(max_length=400)),
                ('hash', models.CharField(max_length=2000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAH.doctor')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAH.pacient')),
            ],
        ),
    ]
