# Generated by Django 3.2.16 on 2022-12-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0007_remove_consult_doctor_remove_consult_pacient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultroomreservation',
            name='consult',
        ),
        migrations.RemoveField(
            model_name='consultroomreservation',
            name='room',
        ),
        migrations.DeleteModel(
            name='ExternalLabs',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Consult',
        ),
        migrations.DeleteModel(
            name='ConsultRoomReservation',
        ),
        migrations.DeleteModel(
            name='Pacient',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
