# Generated by Django 4.1.4 on 2022-12-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0009_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
