# Generated by Django 4.1.4 on 2022-12-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0012_dddd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dddd',
            new_name='UserProfilee',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
