# Generated by Django 4.1.4 on 2022-12-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0007_remove_consult_doctor_remove_consult_pacient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pacient',
        ),
    ]
