# Generated by Django 4.1.4 on 2022-12-20 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0010_rename_doctorprofile_doctorprofilee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofilee',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorprofilee',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
