# Generated by Django 4.1.4 on 2022-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0011_remove_doctorprofilee_user_doctorprofilee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultroomreservation',
            name='consult',
        ),
        migrations.AddField(
            model_name='consultroomreservation',
            name='consult_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultroomreservation',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultroomreservation',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
