# Generated by Django 4.1.4 on 2022-12-21 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0012_remove_consultroomreservation_consult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallabs',
            name='hash',
        ),
        migrations.AlterField(
            model_name='externallabs',
            name='consult_lab_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externallabs',
            name='form_update_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
