# Generated by Django 4.1.4 on 2022-12-21 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0013_remove_externallabs_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallabs',
            name='hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
