# Generated by Django 4.1.4 on 2022-12-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0014_externallabs_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLabProfilee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('lab_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
