# Generated by Django 3.2.16 on 2022-12-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0016_alter_externallabprofilee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallabs',
            name='hash',
            field=models.CharField(max_length=10000),
        ),
    ]
