# Generated by Django 4.1.3 on 2022-12-01 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult_date', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(blank=True, null=True)),
                ('floor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Orthopedy', 'Orthopedy'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology')], max_length=150)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=150)),
                ('phone_number', models.FloatField(blank=True, null=True)),
                ('birth_date', models.FloatField(blank=True, null=True)),
                ('card_id', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=150)),
                ('birth_date', models.FloatField(blank=True, null=True)),
                ('card_id', models.FloatField(blank=True, null=True)),
                ('speciality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SAH.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SAH.consult')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SAH.room')),
            ],
        ),
        migrations.AddField(
            model_name='consult',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAH.doctor'),
        ),
        migrations.AddField(
            model_name='consult',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAH.pacient'),
        ),
    ]
