# Generated by Django 4.1.3 on 2022-12-01 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0002_consult_date_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='card_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='id_card',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='pacient',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacient',
            name='id_card',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='consult',
            name='consult_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
