# Generated by Django 4.1.3 on 2022-12-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0003_remove_doctor_card_id_remove_pacient_card_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='specialization',
        ),
    ]
