# Generated by Django 4.1.3 on 2022-12-02 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAH', '0007_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacient',
            name='id_card',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
